apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/created-by: modeldynamics-helix
    app.kubernetes.io/managed-by: modeldynamics
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: helix-application
  name: test1-mlflow
  namespace: argocd
spec:
  destination:
    namespace: helix-test1
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: envFrom[0].secretRef.name
        value: aws-credentials
      - name: mlflow.bucket
        value: s3://helix-test
      - name: modeldynamics.internal.application.name
        value: test1-mlflow
      - name: modeldynamics.internal.project.name
        value: test1
      valueFiles:
      - values.yaml
    path: charts/incubator/mlflow
    repoURL: https://github.com/combinator-ml/charts
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
      limit: -1
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=background
    - PruneLast=true
